#pragma config(Motor,  port2,           FrontLeftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           FrontRightMotor, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           RearLeftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           RearRightMotor, tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//constants for the slew rate
const float maxChangeRateY = 1;
const float maxChangeRateX = 1;

//minimum threshold for joystick input
const int threshold = 8;

//track the old speeds for the slew rate function
float oldSpeedY = 0;
float oldSpeedX = 0;

//slew rate function to limit how much a value can change by
//oldSpeed: the previous value
//newSpeed: the new value that's not limited
//maxChangeRate: the maximum amount of change that can occur between oldSpeed and newSpeed
//returns the limited speed
float slewRate(float oldSpeed, float newSpeed, float maxChangeRate){
	//gets the raw change: how much acceleration is applied at once
	float change = newSpeed - oldSpeed;
	//if the raw change is over the max: set the raw change to maxChangeRate
	if (fabs(change) > maxChangeRate){
		if (change > 0){
			change = maxChangeRate * 1;
		}
		if (change < 0) {
			change = maxChangeRate * -1;
		}
	}
	//return oldSpeed with maxChangeRate to cap the old speed to a limit
	return oldSpeed + change;
}

//controls the drivetrain wheels
//rightSpeed (-127 to 127): sets all the right motors to rightSpeed
//leftSpeed (-127 to 127): sets all the left motors to leftSpeed
void runWheels(float rightSpeed, float leftSpeed){
	motor[FrontLeftMotor]  = leftSpeed;
	motor[RearLeftMotor]  = leftSpeed;
	motor[FrontRightMotor] = rightSpeed;
	motor[RearRightMotor] = rightSpeed;
}

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main ()
{
	while(1 == 1)
	{
		//variables for the right and left controller axis speeds
		float rightAxis;
		float leftAxis;

		//ignores controller movements that are under threshold to prevent controller drift
		if(abs(vexRT[Ch3]) > threshold)
		{
			leftAxis = slewRate(oldSpeedY, vexRT[Ch3], maxChangeRateY);
		}
		else
		{
			leftAxis = slewRate(oldSpeedY, 0, maxChangeRateY);
		}

		//ignores controller movements that are under threshold to prevent controller drift
		if(abs(vexRT[Ch1]) > threshold)
		{
			rightAxis = slewRate(oldSpeedX, vexRT[Ch1], maxChangeRateX);
		}
		else
		{
			rightAxis = slewRate(oldSpeedX, 0, maxChangeRateX);
		}

		//arcade drive: left joystick is forwards/backwards; right joystick is left/right
		float rightSpeed = leftAxis - rightAxis;
		float leftSpeed =  leftAxis + rightAxis;

		//normalization for the drivetrain: insures wheels stay below the max speed, but keep the same ratio
		float maxSpeed;
		if (fabs(rightSpeed) > fabs(leftSpeed)){
			maxSpeed = fabs(rightSpeed);
		}
		else {
			maxSpeed = fabs(leftSpeed);
		}
		if (maxSpeed > 127){
			leftSpeed = (leftSpeed / maxSpeed) * 127;
			rightSpeed = (rightSpeed / maxSpeed) * 127;
		}

		//sets wheels speeds
		runWheels(rightSpeed, leftSpeed);

		//reset old speeds to current speeds
		oldSpeedX = rightAxis;
		oldSpeedY = leftAxis;
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
